"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Unload = exports.SneakCaptureCity = exports.SneakAttack = exports.Sleep = exports.SetHomeCity = exports.PlantForest = exports.Pillage = exports.NoOrders = exports.Move = exports.GoTo = exports.FoundCity = exports.Fortify = exports.Embark = exports.Disembark = exports.Disband = exports.ClearSwamp = exports.ClearJungle = exports.ClearForest = exports.CaptureCity = exports.BuildRoad = exports.BuildRailroad = exports.BuildMine = exports.BuildIrrigation = exports.Attack = void 0;
var Attack_1 = require("./Actions/Attack");
Object.defineProperty(exports, "Attack", { enumerable: true, get: function () { return Attack_1.Attack; } });
var BuildIrrigation_1 = require("./Actions/BuildIrrigation");
Object.defineProperty(exports, "BuildIrrigation", { enumerable: true, get: function () { return BuildIrrigation_1.BuildIrrigation; } });
var BuildMine_1 = require("./Actions/BuildMine");
Object.defineProperty(exports, "BuildMine", { enumerable: true, get: function () { return BuildMine_1.BuildMine; } });
var BuildRailroad_1 = require("./Actions/BuildRailroad");
Object.defineProperty(exports, "BuildRailroad", { enumerable: true, get: function () { return BuildRailroad_1.BuildRailroad; } });
var BuildRoad_1 = require("./Actions/BuildRoad");
Object.defineProperty(exports, "BuildRoad", { enumerable: true, get: function () { return BuildRoad_1.BuildRoad; } });
var CaptureCity_1 = require("./Actions/CaptureCity");
Object.defineProperty(exports, "CaptureCity", { enumerable: true, get: function () { return CaptureCity_1.CaptureCity; } });
var ClearForest_1 = require("./Actions/ClearForest");
Object.defineProperty(exports, "ClearForest", { enumerable: true, get: function () { return ClearForest_1.ClearForest; } });
var ClearJungle_1 = require("./Actions/ClearJungle");
Object.defineProperty(exports, "ClearJungle", { enumerable: true, get: function () { return ClearJungle_1.ClearJungle; } });
var ClearSwamp_1 = require("./Actions/ClearSwamp");
Object.defineProperty(exports, "ClearSwamp", { enumerable: true, get: function () { return ClearSwamp_1.ClearSwamp; } });
var Disband_1 = require("./Actions/Disband");
Object.defineProperty(exports, "Disband", { enumerable: true, get: function () { return Disband_1.Disband; } });
var Disembark_1 = require("./Actions/Disembark");
Object.defineProperty(exports, "Disembark", { enumerable: true, get: function () { return Disembark_1.Disembark; } });
var Embark_1 = require("./Actions/Embark");
Object.defineProperty(exports, "Embark", { enumerable: true, get: function () { return Embark_1.Embark; } });
var Fortify_1 = require("./Actions/Fortify");
Object.defineProperty(exports, "Fortify", { enumerable: true, get: function () { return Fortify_1.Fortify; } });
var FoundCity_1 = require("./Actions/FoundCity");
Object.defineProperty(exports, "FoundCity", { enumerable: true, get: function () { return FoundCity_1.FoundCity; } });
var GoTo_1 = require("./Actions/GoTo");
Object.defineProperty(exports, "GoTo", { enumerable: true, get: function () { return GoTo_1.GoTo; } });
var Move_1 = require("./Actions/Move");
Object.defineProperty(exports, "Move", { enumerable: true, get: function () { return Move_1.Move; } });
var NoOrders_1 = require("./Actions/NoOrders");
Object.defineProperty(exports, "NoOrders", { enumerable: true, get: function () { return NoOrders_1.NoOrders; } });
var Pillage_1 = require("./Actions/Pillage");
Object.defineProperty(exports, "Pillage", { enumerable: true, get: function () { return Pillage_1.Pillage; } });
var PlantForest_1 = require("./Actions/PlantForest");
Object.defineProperty(exports, "PlantForest", { enumerable: true, get: function () { return PlantForest_1.PlantForest; } });
var SetHomeCity_1 = require("./Actions/SetHomeCity");
Object.defineProperty(exports, "SetHomeCity", { enumerable: true, get: function () { return SetHomeCity_1.SetHomeCity; } });
var Sleep_1 = require("./Actions/Sleep");
Object.defineProperty(exports, "Sleep", { enumerable: true, get: function () { return Sleep_1.Sleep; } });
var SneakAttack_1 = require("./Actions/SneakAttack");
Object.defineProperty(exports, "SneakAttack", { enumerable: true, get: function () { return SneakAttack_1.SneakAttack; } });
var SneakCaptureCity_1 = require("./Actions/SneakCaptureCity");
Object.defineProperty(exports, "SneakCaptureCity", { enumerable: true, get: function () { return SneakCaptureCity_1.SneakCaptureCity; } });
var Unload_1 = require("./Actions/Unload");
Object.defineProperty(exports, "Unload", { enumerable: true, get: function () { return Unload_1.Unload; } });
//# sourceMappingURL=Actions.js.map