"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Unload = exports.SubvertCity = exports.StealTechnology = exports.SneakStealTechnology = exports.SneakInciteRevolt = exports.SneakCaptureCity = exports.SneakAttack = exports.Sleep = exports.SetHomeCity = exports.PlantForest = exports.Pillage = exports.NoOrders = exports.Move = exports.MeetWithKing = exports.JoinCity = exports.InvestigateCity = exports.IndustrialSabotage = exports.InciteRevolt = exports.HelpBuildWonder = exports.GoTo = exports.FoundCity = exports.Fortify = exports.Explore = exports.EstablishTradeRoute = exports.EstablishEmbassy = exports.Embark = exports.Disembark = exports.Disband = exports.ClearSwamp = exports.ClearJungle = exports.ClearForest = exports.CaptureCity = exports.BuildRoad = exports.BuildRailroad = exports.BuildMine = exports.BuildIrrigation = exports.BribeUnit = exports.Automate = exports.Attack = void 0;
var Attack_1 = require("./Actions/Attack");
Object.defineProperty(exports, "Attack", { enumerable: true, get: function () { return Attack_1.Attack; } });
var Automate_1 = require("./Actions/Automate");
Object.defineProperty(exports, "Automate", { enumerable: true, get: function () { return Automate_1.Automate; } });
var BribeUnit_1 = require("./Actions/BribeUnit");
Object.defineProperty(exports, "BribeUnit", { enumerable: true, get: function () { return BribeUnit_1.BribeUnit; } });
var BuildIrrigation_1 = require("./Actions/BuildIrrigation");
Object.defineProperty(exports, "BuildIrrigation", { enumerable: true, get: function () { return BuildIrrigation_1.BuildIrrigation; } });
var BuildMine_1 = require("./Actions/BuildMine");
Object.defineProperty(exports, "BuildMine", { enumerable: true, get: function () { return BuildMine_1.BuildMine; } });
var BuildRailroad_1 = require("./Actions/BuildRailroad");
Object.defineProperty(exports, "BuildRailroad", { enumerable: true, get: function () { return BuildRailroad_1.BuildRailroad; } });
var BuildRoad_1 = require("./Actions/BuildRoad");
Object.defineProperty(exports, "BuildRoad", { enumerable: true, get: function () { return BuildRoad_1.BuildRoad; } });
var CaptureCity_1 = require("./Actions/CaptureCity");
Object.defineProperty(exports, "CaptureCity", { enumerable: true, get: function () { return CaptureCity_1.CaptureCity; } });
var ClearForest_1 = require("./Actions/ClearForest");
Object.defineProperty(exports, "ClearForest", { enumerable: true, get: function () { return ClearForest_1.ClearForest; } });
var ClearJungle_1 = require("./Actions/ClearJungle");
Object.defineProperty(exports, "ClearJungle", { enumerable: true, get: function () { return ClearJungle_1.ClearJungle; } });
var ClearSwamp_1 = require("./Actions/ClearSwamp");
Object.defineProperty(exports, "ClearSwamp", { enumerable: true, get: function () { return ClearSwamp_1.ClearSwamp; } });
var Disband_1 = require("./Actions/Disband");
Object.defineProperty(exports, "Disband", { enumerable: true, get: function () { return Disband_1.Disband; } });
var Disembark_1 = require("./Actions/Disembark");
Object.defineProperty(exports, "Disembark", { enumerable: true, get: function () { return Disembark_1.Disembark; } });
var Embark_1 = require("./Actions/Embark");
Object.defineProperty(exports, "Embark", { enumerable: true, get: function () { return Embark_1.Embark; } });
var EstablishEmbassy_1 = require("./Actions/EstablishEmbassy");
Object.defineProperty(exports, "EstablishEmbassy", { enumerable: true, get: function () { return EstablishEmbassy_1.EstablishEmbassy; } });
var EstablishTradeRoute_1 = require("./Actions/EstablishTradeRoute");
Object.defineProperty(exports, "EstablishTradeRoute", { enumerable: true, get: function () { return EstablishTradeRoute_1.EstablishTradeRoute; } });
var Explore_1 = require("./Actions/Explore");
Object.defineProperty(exports, "Explore", { enumerable: true, get: function () { return Explore_1.Explore; } });
var Fortify_1 = require("./Actions/Fortify");
Object.defineProperty(exports, "Fortify", { enumerable: true, get: function () { return Fortify_1.Fortify; } });
var FoundCity_1 = require("./Actions/FoundCity");
Object.defineProperty(exports, "FoundCity", { enumerable: true, get: function () { return FoundCity_1.FoundCity; } });
var GoTo_1 = require("./Actions/GoTo");
Object.defineProperty(exports, "GoTo", { enumerable: true, get: function () { return GoTo_1.GoTo; } });
var HelpBuildWonder_1 = require("./Actions/HelpBuildWonder");
Object.defineProperty(exports, "HelpBuildWonder", { enumerable: true, get: function () { return HelpBuildWonder_1.HelpBuildWonder; } });
var InciteRevolt_1 = require("./Actions/InciteRevolt");
Object.defineProperty(exports, "InciteRevolt", { enumerable: true, get: function () { return InciteRevolt_1.InciteRevolt; } });
var IndustrialSabotage_1 = require("./Actions/IndustrialSabotage");
Object.defineProperty(exports, "IndustrialSabotage", { enumerable: true, get: function () { return IndustrialSabotage_1.IndustrialSabotage; } });
var InvestigateCity_1 = require("./Actions/InvestigateCity");
Object.defineProperty(exports, "InvestigateCity", { enumerable: true, get: function () { return InvestigateCity_1.InvestigateCity; } });
var JoinCity_1 = require("./Actions/JoinCity");
Object.defineProperty(exports, "JoinCity", { enumerable: true, get: function () { return JoinCity_1.JoinCity; } });
var MeetWithKing_1 = require("./Actions/MeetWithKing");
Object.defineProperty(exports, "MeetWithKing", { enumerable: true, get: function () { return MeetWithKing_1.MeetWithKing; } });
var Move_1 = require("./Actions/Move");
Object.defineProperty(exports, "Move", { enumerable: true, get: function () { return Move_1.Move; } });
var NoOrders_1 = require("./Actions/NoOrders");
Object.defineProperty(exports, "NoOrders", { enumerable: true, get: function () { return NoOrders_1.NoOrders; } });
var Pillage_1 = require("./Actions/Pillage");
Object.defineProperty(exports, "Pillage", { enumerable: true, get: function () { return Pillage_1.Pillage; } });
var PlantForest_1 = require("./Actions/PlantForest");
Object.defineProperty(exports, "PlantForest", { enumerable: true, get: function () { return PlantForest_1.PlantForest; } });
var SetHomeCity_1 = require("./Actions/SetHomeCity");
Object.defineProperty(exports, "SetHomeCity", { enumerable: true, get: function () { return SetHomeCity_1.SetHomeCity; } });
var Sleep_1 = require("./Actions/Sleep");
Object.defineProperty(exports, "Sleep", { enumerable: true, get: function () { return Sleep_1.Sleep; } });
var SneakAttack_1 = require("./Actions/SneakAttack");
Object.defineProperty(exports, "SneakAttack", { enumerable: true, get: function () { return SneakAttack_1.SneakAttack; } });
var SneakCaptureCity_1 = require("./Actions/SneakCaptureCity");
Object.defineProperty(exports, "SneakCaptureCity", { enumerable: true, get: function () { return SneakCaptureCity_1.SneakCaptureCity; } });
var SneakInciteRevolt_1 = require("./Actions/SneakInciteRevolt");
Object.defineProperty(exports, "SneakInciteRevolt", { enumerable: true, get: function () { return SneakInciteRevolt_1.SneakInciteRevolt; } });
var SneakStealTechnology_1 = require("./Actions/SneakStealTechnology");
Object.defineProperty(exports, "SneakStealTechnology", { enumerable: true, get: function () { return SneakStealTechnology_1.SneakStealTechnology; } });
var StealTechnology_1 = require("./Actions/StealTechnology");
Object.defineProperty(exports, "StealTechnology", { enumerable: true, get: function () { return StealTechnology_1.StealTechnology; } });
var SubvertCity_1 = require("./Actions/SubvertCity");
Object.defineProperty(exports, "SubvertCity", { enumerable: true, get: function () { return SubvertCity_1.SubvertCity; } });
var Unload_1 = require("./Actions/Unload");
Object.defineProperty(exports, "Unload", { enumerable: true, get: function () { return Unload_1.Unload; } });
//# sourceMappingURL=Actions.js.map