"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Warrior = exports.Trireme = exports.Transport = exports.Tank = exports.Swordman = exports.Submarine = exports.Spearman = exports.Settlers = exports.Sail = exports.Rifleman = exports.Nuclear = exports.Musketman = exports.MechanizedInfantry = exports.Knight = exports.Ironclad = exports.Horseman = exports.Frigate = exports.Fighter = exports.Diplomat = exports.Cruiser = exports.Chariot = exports.Catapult = exports.Carrier = exports.Caravan = exports.Cannon = exports.Bomber = exports.Battleship = exports.Artillery = void 0;
var Artillery_1 = require("./Units/Artillery");
Object.defineProperty(exports, "Artillery", { enumerable: true, get: function () { return Artillery_1.Artillery; } });
var Battleship_1 = require("./Units/Battleship");
Object.defineProperty(exports, "Battleship", { enumerable: true, get: function () { return Battleship_1.Battleship; } });
var Bomber_1 = require("./Units/Bomber");
Object.defineProperty(exports, "Bomber", { enumerable: true, get: function () { return Bomber_1.Bomber; } });
var Cannon_1 = require("./Units/Cannon");
Object.defineProperty(exports, "Cannon", { enumerable: true, get: function () { return Cannon_1.Cannon; } });
var Caravan_1 = require("./Units/Caravan");
Object.defineProperty(exports, "Caravan", { enumerable: true, get: function () { return Caravan_1.Caravan; } });
var Carrier_1 = require("./Units/Carrier");
Object.defineProperty(exports, "Carrier", { enumerable: true, get: function () { return Carrier_1.Carrier; } });
var Catapult_1 = require("./Units/Catapult");
Object.defineProperty(exports, "Catapult", { enumerable: true, get: function () { return Catapult_1.Catapult; } });
var Chariot_1 = require("./Units/Chariot");
Object.defineProperty(exports, "Chariot", { enumerable: true, get: function () { return Chariot_1.Chariot; } });
var Cruiser_1 = require("./Units/Cruiser");
Object.defineProperty(exports, "Cruiser", { enumerable: true, get: function () { return Cruiser_1.Cruiser; } });
var Diplomat_1 = require("./Units/Diplomat");
Object.defineProperty(exports, "Diplomat", { enumerable: true, get: function () { return Diplomat_1.Diplomat; } });
var Fighter_1 = require("./Units/Fighter");
Object.defineProperty(exports, "Fighter", { enumerable: true, get: function () { return Fighter_1.Fighter; } });
var Frigate_1 = require("./Units/Frigate");
Object.defineProperty(exports, "Frigate", { enumerable: true, get: function () { return Frigate_1.Frigate; } });
var Horseman_1 = require("./Units/Horseman");
Object.defineProperty(exports, "Horseman", { enumerable: true, get: function () { return Horseman_1.Horseman; } });
var Ironclad_1 = require("./Units/Ironclad");
Object.defineProperty(exports, "Ironclad", { enumerable: true, get: function () { return Ironclad_1.Ironclad; } });
var Knight_1 = require("./Units/Knight");
Object.defineProperty(exports, "Knight", { enumerable: true, get: function () { return Knight_1.Knight; } });
var MechanizedInfantry_1 = require("./Units/MechanizedInfantry");
Object.defineProperty(exports, "MechanizedInfantry", { enumerable: true, get: function () { return MechanizedInfantry_1.MechanizedInfantry; } });
var Musketman_1 = require("./Units/Musketman");
Object.defineProperty(exports, "Musketman", { enumerable: true, get: function () { return Musketman_1.Musketman; } });
var Nuclear_1 = require("./Units/Nuclear");
Object.defineProperty(exports, "Nuclear", { enumerable: true, get: function () { return Nuclear_1.Nuclear; } });
var Rifleman_1 = require("./Units/Rifleman");
Object.defineProperty(exports, "Rifleman", { enumerable: true, get: function () { return Rifleman_1.Rifleman; } });
var Sail_1 = require("./Units/Sail");
Object.defineProperty(exports, "Sail", { enumerable: true, get: function () { return Sail_1.Sail; } });
var Settlers_1 = require("./Units/Settlers");
Object.defineProperty(exports, "Settlers", { enumerable: true, get: function () { return Settlers_1.Settlers; } });
var Spearman_1 = require("./Units/Spearman");
Object.defineProperty(exports, "Spearman", { enumerable: true, get: function () { return Spearman_1.Spearman; } });
var Submarine_1 = require("./Units/Submarine");
Object.defineProperty(exports, "Submarine", { enumerable: true, get: function () { return Submarine_1.Submarine; } });
var Swordman_1 = require("./Units/Swordman");
Object.defineProperty(exports, "Swordman", { enumerable: true, get: function () { return Swordman_1.Swordman; } });
var Tank_1 = require("./Units/Tank");
Object.defineProperty(exports, "Tank", { enumerable: true, get: function () { return Tank_1.Tank; } });
var Transport_1 = require("./Units/Transport");
Object.defineProperty(exports, "Transport", { enumerable: true, get: function () { return Transport_1.Transport; } });
var Trireme_1 = require("./Units/Trireme");
Object.defineProperty(exports, "Trireme", { enumerable: true, get: function () { return Trireme_1.Trireme; } });
var Warrior_1 = require("./Units/Warrior");
Object.defineProperty(exports, "Warrior", { enumerable: true, get: function () { return Warrior_1.Warrior; } });
//# sourceMappingURL=Units.js.map